### ISSUE TITLE
Links does not work in pdf

### ISSUE THREAD

**Issue by rodrigosantos2701** [gregnb/react-to-print#424]
Using  the `a` html tag ,  the link appears on pdf but doesn't work. The link works as image and does not redirect as a link.

code example: (**see on codesandbox**: https://codesandbox.io/s/rodrigo-react-to-print-3q876?file=/src/App.js:0-637)

```jsx
import React from "react";
import ReactToPrint from "react-to-print";

class ComponentToPrint extends React.Component {

  render() {
    return (
      <div>
      
        < a href="www.google.com"> link to google</a>  <== i need that link works after print it
      </div>
    );
  }
}

class Example extends React.Component {
  render() {
    return (
      <div>
        <ReactToPrint
          trigger={() => < a href="#">Print this out!</a>}
          content={() => this.componentRef}
        />
        <ComponentToPrint ref={el => (this.componentRef = el)} />
      </div>
    );
  }
}

export default Example;
```

pdf example after print ( the link does not redirect):

![Captura de Tela (39)](https://user-images.githubusercontent.com/52668782/138952640-89e32366-cba0-4df2-a1dc-62bc2b98316e.png)

**Comment by MatthewHerbst** [comment]
Hi, thanks for sharing your issue. It works just fine for me when I download the PDF using Chrome and view the PDF using the Preview app on MacOS. What browser/pdf view are you using?

**Comment by rodrigosantos2701** [comment]
Hi, using windows 10.
problem solved! 
i changed the default print type from "microsoft print to pdf" to "save pdf file". and it works!
tks ! 
![Captura de Tela (40)_LI](https://user-images.githubusercontent.com/52668782/139273607-8057679c-a19a-4ac4-840f-c0df2d1ff53d.jpg)
