### ISSUE TITLE
codesandbox examples are not loading

### ISSUE THREAD

**Issue by alishefaee** [gregnb/react-to-print#688]
Sandbox gives Out Of Credit for repo owner

**Comment by MatthewHerbst** [comment]
Yeah, they recently changed it so that you have to pay for these unfortunately. I'm trying to find a solution with them or a different website to move the examples to. In the meantime, you can run the examples locally by downloading the repo and then `npm i && npm start`

**Comment by MatthewHerbst** [comment]
The issue with the sandbox should be resolved, thank you for your patience!
